#
spring:
  cloud:
    gateway:
      enabled: true
      #（▲）
      discovery:
        locator:
          enabled: true
      #（▲）http连接
      httpclient:
        pool:
          #Only for type FIXED
          max-connections: 5000
          #Only for type FIXED
          acquire-timeout: 5000
          max-idle-time: 1000
          max-life-time: 1000
        #连接超时
        connect-timeout: 5000
        #读取超时
        response-timeout: 5000
      #（▲）路由
      routes:
        - id: study-springcloud-provider
          #目标服务地址
          uri: lb://study-springcloud-provider
          #路由条件
          predicates:
            - Path=/study-springcloud-provider/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/defaultFallback
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE
#          thread:
#            timeoutInMilliseconds: 3000
#      fallback:
#        enabled: fasle
#      circuitBreaker:
#        enabled: true
#        requestVolumeThreshold: 11
#        sleepWindowInMilliseconds: 123
#        errorThresholdPercentage: 1231
#        forceOpen: true
#        forceClosed: true
