server:
  port: 7200
#
logging:
  config: classpath:logback.xml
#
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://150.158.110.15:7100/
#
spring:
  application:
    name: study-springcloud-gateway
  main:
    web-application-type: servlet
    banner-mode: off
  profiles:
    active: gateway
