#
spring:
  cloud:
    gateway:
      enabled: true
      #（▲）
      discovery:
        locator:
          enabled: true
      #（▲）http连接
      httpclient:
        pool:
          max-connections: 5000
          acquire-timeout: 5000
        connect-timeout: 5000
        response-timeout: 5000
      #（▲）路由
      routes:
        - id: study-springcloud-provider
          #目标服务地址
          uri: lb://study-springcloud-provider
          #路由条件
          predicates:
            - Path=/study-springcloud-provider/**
          filters:
            - StripPrefix=1
            - name: Hystrix
              args:
                name: default
                fallbackUri: forward:/defaultFallback
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          strategy: SEMAPHORE
#          thread:
#            timeoutInMilliseconds: 3000
#      circuitBreaker:
