#====================
#（★）
#====================
spring:
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
      #====================
      #（▲）
      #====================
      routes:
        - id: fs
          uri: lb://fs
          predicates:
            - Path=/house/**


