#
spring:
  cloud:
    gateway:
      #（★）过滤器（全局）
      default-filters:
        #（▲）内置过滤器
#        - AddResponseHeader=X-Response-Default-Name, Default-Value
#        - AddRequestHeader=X-Request-Id, Value
#        - AddRequestParameter=name, value
        - StripPrefix=1
        #（▲）自定义过滤器，springboot 约定自定义过滤器前缀为配置的name，后面最好统一都是GatewayFilterFactory
        - name: WatchDog
        - name: Auth
      #（★）路由
      routes:
        #服务
        - id: study-springcloud-provider
          #目标服务地址，lb代表从注册中心获取服务，且以负载均衡方式转发
          uri: lb://study-springcloud-provider
          #断言
          predicates:
            - Path=/springcloud-provider/**, /aaa/***, /bbb/***
            #（▲）过滤器（局部）
          filters:
            - name: Custom
              args:
                name: root
                age: 30
        #服务
        - id: study-springcloud-consumer-feign
          uri: lb://study-springcloud-consumer-feign
          predicates:
            - Path=/springcloud-consumer-feign/**
        #服务
        - id: study-springcloud-consumer-rest
          uri: lb://study-springcloud-consumer-rest
          predicates:
            - Path=/springcloud-consumer-rest/**
