#
spring:
  #（★）Redis
  redis:
    host: 150.158.110.15
    port: 7379
    database: 0
  cloud:
    gateway:
      enabled: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
       routes:
        - id: study-springcloud-provider
          uri: lb://study-springcloud-provider
          predicates:
            - Path=/springcloud-provider/**
          filters:
            #（★）uri和predicates中path后的第一段路径不能设置成一样，否则限流不生效
            #默认按秒限流；RequestRateLimiterGatewayFilterFactory, RedisRateLimiter
            - name: RequestRateLimiter
              args:
                #使用SpEL按照名称引用Bean
                key-resolver: '#{@uriKeyResolver}'
                redis-rate-limiter:
                  #每次补充令牌数量
                  #令牌桶每秒填充平均速率，允许用户每秒处理多少个请求
                  replenishRate: 5
                  #令牌桶最大容量，突发请求数量
                  #令牌桶最大容量，允许1秒内完成的最大请求数
                  burstCapacity: 50
                  #每次请求消耗令牌的数量
                  requestedTokens: 1
