#
spring:
  cloud:
    gateway:
      #（★）全局过滤器
      default-filters:
        #（▲）内置过滤器
#        - AddResponseHeader=X-Response-Default-Name, Default-Value
#        - AddRequestHeader=X-Request-Id, Value
#        - AddRequestParameter=name, value
        - StripPrefix=1
        #（▲）自定义过滤器，springboot 约定自定义过滤器前缀为配置的name，
        #后面最好统一都是GatewayFilterFactory
        - name: WatchDog
        - name: Custom
          args:
            name: root
            age: 30
      #（★）路由
      routes:
        - id: study-springcloud-provider
          #目标服务地址，lb代表从注册中心获取服务，且以负载均衡方式转发
          uri: lb://study-springcloud-provider
          #断言
          predicates:
            - Path=/springcloud-provider/**, /aaa/***, /bbb/***
          #局部过滤器
        #          filters:
        #            - name: Custom
        #              args:
        #                type: root
        - id: study-springcloud-consumer-feign
            #目标服务地址，lb代表从注册中心获取服务，且以负载均衡方式转发
            uri: lb://study-springcloud-consumer-feign
            #断言
            predicates:
              - Path=/springcloud-consumer-feign/**
            #局部过滤器
#          filters:
#            - name: Custom
#              args:
#                type: root