#
hystrix:
  command:
    default:
      #（★）HystrixCommand如何去执行
      execution:
        #（▲）HystrixCommand.run()的执行是否启用超时时间
        timeout:
          enabled: false
        #（▲）隔离
        isolation:
          #HystrixCommand.run()执行的隔离策略，THREAD/SEMAPHORE
          strategy: SEMAPHORE
          #（▲）线程
          thread:
            #HystrixCommand执行的超时时间
            timeoutInMilliseconds: 3000
            #当HystrixCommand.run()执行超时的时候是否要它中断
            interruptOnTimeout: true
            #当HystrixCommand.run()执行取消时是否要它中断
            interruptOnCancel: true
          #（▲）信号量
          semaphore:
            #信号量的大小，当最大并发请求达到该设置值时，后续的请求将被拒绝
            maxConcurrentRequests: 12
      #（▲★）回退
      fallback:
        enabled: true
      #（▲★）熔断器
#      circuitBreaker:
#        #是否开启熔断器，默认为true
#        enabled: true
#        #在一定的窗口时间内，打开熔断器的最小请求数
#        requestVolumeThreshold: 11
#        #
#        sleepWindowInMilliseconds: 123
#        #窗口时间内多少百分比的请求失败会打开熔断器，默认是50，也就是超过50%的失败了才会打开
#        errorThresholdPercentage: 50
#        #是否强制开启或强制关闭，默认是false
#        forceOpen: true
#        forceClosed: true
