#
spring:
  cloud:
    gateway:
      #（★）启用网关
      enabled: true
      #（★）注册发现
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #（★）http连接
      httpclient:
        pool:
          #elastic/fixed/disabled
          type: elastic
          #fixed类型可用
          max-connections: 5000
          acquire-timeout: 5000
          #最大空闲时间
          max-idle-time: 1000
          #最大生命周期
          max-life-time: 1000
        #连接和读取超时
        connect-timeout: 5000
        response-timeout: 5000
      #（★）全局过滤器
      default-filters:
#        - AddResponseHeader=X-Response-Default-Name, Default-Value
#        - AddRequestHeader=X-Request-Id, Value
#        - AddRequestParameter=name, value
#        - StripPrefix=1
      #（★）路由
      routes:
        - id: study-springcloud-provider
          #目标服务地址，lb代表从注册中心获取服务，且以负载均衡方式转发
          uri: lb://study-springcloud-provider
          #断言
          predicates:
            - Path=/springcloud-provider/**
          #局部过滤器
          filters:
            - StripPrefix=1
