#
spring:
  redis:
    host: 150.158.110.15
    port: 7379
    database: 0
#    password: abc123
  cloud:
    gateway:
      enabled: true
      #（★）
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      #（★）http连接
      httpclient:
        pool:
          #Only for type FIXED
          max-connections: 5000
          acquire-timeout: 5000
          #
          max-idle-time: 1000
          max-life-time: 1000
        #连接和读取超时
        connect-timeout: 5000
        response-timeout: 5000
      #（★）全局过滤器
      default-filters:
        - StripPrefix=1
        #HystrxGatewayFilterFactroy
        - name: Hystrix
          args:
            name: default
            #fallbackUri: forward:/defaultFallback
        - name: RequestRateLimiter
          args:
            #使用SpEL表达式从Spring容器中获取Bean对象
            key-resolver: '#{@uriKeyResolver}'
            #每秒最大访问次数；令牌桶每秒填充平均速率
            redis-rate-limiter.replenishRate: 1
            #令牌桶最大容量；令牌桶上线
            redis-rate-limiter.burstCapacity: 2
      #（★）路由
      routes:
        - id: study-springcloud-provider
          #目标服务地址，lb代表从注册中心获取服务，且以负载均衡方式转发
          uri: lb://study-springcloud-provider
          #路由条件
          predicates:
            - Path=/study-springcloud-provider/**
          #过滤规则
          filters:
            #（▲）限流
            - name: RequestRateLimiter
              args:
                #使用SpEL表达式从Spring容器中获取Bean对象
                key-resolver: '#{@uriKeyResolver}'
                #每秒最大访问次数；令牌桶每秒填充平均速率
                redis-rate-limiter.replenishRate: 1
                #令牌桶最大容量；令牌桶上线
                redis-rate-limiter.burstCapacity: 2
