#
hystrix:
  threadpool:
    default:
      coreSize: 10
      maxQueueSize: -1
      queueSizeRejectionThreshold: 1000
  command:
    default:
      #（★）HystrixCommand如何去执行
      execution:
        #（▲）HystrixCommand.run()的执行是否启用超时时间
        timeout:
          enabled: false
        #（▲）隔离
        isolation:
          #HystrixCommand.run()执行的隔离策略，THREAD/SEMAPHORE
          strategy: SEMAPHORE
          #（▲）线程
          thread:
            #HystrixCommand执行的超时时间
            timeoutInMilliseconds: 3000
            #当HystrixCommand.run()执行超时的时候是否要它中断
            interruptOnTimeout: true
            #当HystrixCommand.run()执行取消时是否要它中断
            interruptOnCancel: true
          #（▲）信号量
          semaphore:
            #信号量的大小，当最大并发请求达到该设置值时，后续的请求将被拒绝
            maxConcurrentRequests: 12
      #（★）回退降级
      fallback:
        enabled: true
      #（★）熔断器
      circuitBreaker:
        #是否开启熔断器，默认为true
        enabled: true
        #在滚动时间窗中，断路器熔断的最小请求数
        requestVolumeThreshold: 11
        #
        sleepWindowInMilliseconds: 123
        #窗口时间内多少百分比的请求失败会打开熔断器，默认是50，也就是超过50%的失败了才会打开
        errorThresholdPercentage: 50
        #断路器将强制进入“打开”状态，它会拒绝所有请求
        forceOpen: true
        #
        forceClosed: true
